In [8]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_excel('data_nyse_screener.xlsx', 'sheet2')
data

,Symbol,Name,IPO Year,Sector,Industry;
0,A,Agilent Technologies,1999.0,Industrials,Electrical Products;
1,AAIC,Arlington Asset Investment,NaN,Real Estate,Real Estate Investment Trusts;
2,AAP,Advance Auto Parts,NaN,Consumer Discretionary,Auto Home Supply Stores;
3,AAT,American Assets Trust,2011.0,Real Estate,Real Estate Investment Trusts;
4,AB,AllianceBernstein Holding,NaN,Finance,Investment Managers;
...,...,...,...,...,...
1189,YELP,Yelp,2012.0,Technology,Internet and Information Services;
1190,YPF,YPF,1993.0,Energy,Integrated oil Companies;
1191,YUM,Yum Brands,NaN,Consumer Discretionary,Restaurants;
1192,ZBH,Zimmer Biomet Holdings,NaN,Health Care,Industrial Specialties;
1193,ZWS,Zurn Elkay Water Solutions,2012.0,Utilities,Environmental Services;

In [10]:
data.to_csv("z_test.txt", columns=["Symbol"], header=False, index=False)